apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: anchore-engine
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: anchore
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: anchore-engine
    repoURL: https://charts.anchore.io
    targetRevision: 1.*
    helm:
      values: |
        anchoreGlobal:
          defaultAdminPassword: anchore123
          policyBundles:
            custom_policy_bundle1.json: |-
              {
                "id": "default1",
                "version": "1_0",
                "name": "My Default bundle",
                "comment": "My system's default bundle",
                "whitelisted_images": [],
                "blacklisted_images": [
                  {
                  "name": "BlacklistLatest",
                  "registry": "*",
                  "repository": "*",
                  "image": { "type": "tag", "value": "latest" }
                  }
                ],
                "mappings": [],
                "whitelists": [],
                "policies": []
              }
        anchoreAnalyzer:
          malware:
            clamav:
              enabled: true
              db_update_enabled: true
          resources:
            limits:
              cpu: 1
              memory: 4G
            requests:
              cpu: 1
              memory: 1G
        anchorePolicyEngine:
          resources:
            limits:
              cpu: 1
              memory: 4G
            requests:
              cpu: 100m
              memory: 1G
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true