apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: anchore-engine
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: anchore
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: anchore-engine
    repoURL: https://charts.anchore.io
    targetRevision: 1.*
    helm:
      values: |
        anchoreAnalyzer:
          malware:
            clamav:
              enabled: true
              db_update_enabled: true
          resources:
            limits:
              cpu: 1
              memory: 4G
            requests:
              cpu: 1
              memory: 1G
        anchoreApi:
          service:
            type: LoadBalancer
            port: 8228
            annotations: {}
            label: {}
        anchorePolicyEngine:
          resources:
            limits:
              cpu: 1
              memory: 4G
            requests:
              cpu: 100m
              memory: 1G
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true