apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infrastructure-apps
  # You'll usually want to add your resources to the argocd namespace.
  namespace: argocd
  # Add a this finalizer ONLY if you want these to cascade delete.
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # Destination cluster and namespace to deploy the application
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  # The project the application belongs to.
  project: default
  source:
    directory:
      jsonnet: {}
      recurse: true
    path: gitops/infrastructure
    repoURL: https://github.com/AlexanderSarson/digitalocean_challenge.git
    targetRevision: HEAD